baseURL = "https://localhost/hernangalvan"
defaultContentLanguage = "en"
disqusShortname = "test"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "Hernan Galvan"
[author]
  gravatarEmail = "hernangalvan79@gmail.com"
  homepageText = "Hernan Galvan"
  name = "Hernán Galván"
  rss = "/posts/index.xml"
[imaging]
  anchor = "smart"
  resampleFilter = "box"
  quality = 75
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[params]
  adsenseClient = ''
  adsenseSlot = ''
  description = "A blog about everything."
  licence = ""
  displayPostLanguage = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
[markup.goldmark.renderer]
unsafe = true
